### ISSUE TITLE
Notices generated by WP-CLI commands

### ISSUE THREAD

**Issue by viktorix** [ClassicPress/directory#8] opened 2022-11-18 16:35 UTC
**Describe the bug**
When using WP-CLI commands, they can generate PHP notices since certain things are not available in CLI.

```
[18-Nov-2022 15:58:43 UTC] PHP Notice:  Trying to get property 'display_name' of non-object in /public_html/wp-content/plugins/kts-email-logs/email-logs.php on line 34
[18-Nov-2022 15:58:43 UTC] PHP Notice:  Undefined index: SERVER_NAME in /public_html/wp-includes/pluggable.php on line 366
```
This is a not a major issue, since WP-CLI won't be used often.

**To Reproduce**
1. Log in to SSH to use WP-CLI
2. Go to web root directory (public_html)
3. Run `"wp_mail( 'youremail@email.com', 'Test email', 'This is a test.', array('Content-Type: text/html; charset=UTF-8') );" --allow-root`
4. The notices will be displayed in terminal and logged to debug.log
5. They do prevent emails from being sent.

**Expected behavior**
No notices. Emails go through sent from WP-CLI.

**Additional context**
The problem is you can't get `$user = get_user_by( 'email', $args['to'] );` in CLI, there's no user logged in. Maybe add a condition to check for WP-CLI environment and if true set an admin user, maybe ID 1, as a default WP-CLI user.

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    // Do WP-CLI specific things.
}
```

**Comment by viktorix** [comment] 2022-11-18 16:37
So the second SERVER_NAME notice can be fixed by adding the following to the wp-config.php, but maybe it should be added to mu-plugin?

```
if ( defined( 'WP_CLI' ) && WP_CLI ) {
    if(!isset($_SERVER['SERVER_NAME'] )) {
		$_SERVER['SERVER_NAME'] = 'directory.classicpress.net';
	}
}
```

**Comment by xxsimoxx** [comment] 2022-11-25 13:53
Seems to be a CP issue that is solved in 1.5.
I can reproduce it in a few sites with CP 1.4.4 and not in the ones with the nightly-build.

**Comment by xxsimoxx** [comment] 2022-11-25 14:29
Going deeper that was addressed by WP-r48601 that we backported [here](https://github.com/ClassicPress/ClassicPress/pull/1021).

**Comment by viktorix** [comment] 2022-11-25 17:25
Once RC1 is released, we can test it and close this issue.

**Comment by viktorix** [comment] 2022-12-22 19:50
I've tested this with 1.5.0-rc2 and `SERVER_NAME` notice is gone, but the display_name notice is still there. From my original report:

The problem is you can't get `$user = get_user_by( 'email', $args['to'] );` in CLI, there's no user logged in. Maybe add a condition to check for WP-CLI environment and if true set an admin user, maybe ID 1, as a default WP-CLI user?

**Comment by KTS915** [comment] 2022-12-22 23:36
>if true set an admin user, maybe ID 1, as a default WP-CLI user

Please don't set the user ID to 1 by default. It's actually recommended practice NOT to have an administrator account as ID 1 (typically by creating a second admin account and deleting the original).

**Comment by xxsimoxx** [comment] 2022-12-30 13:14
Ok, going deeper, it's not a wp-cli issue but a general, so I've opened an [issue](https://github.com/KTS915/Email-Logs/issues/1).
Waiting for the plugin update, I'll try to fix it.

**Closed as completed** 2022-12-30 13:21 UTC
Labels: bug, status: discussion
